export interface Theme {
  id: string;
  name: string;
  colors: Record<string, string>;
}

export const themes: Theme[] = [
  {
    id: 'dark',
    name: 'Dark',
    colors: {
      background: '#0a0a0b',
      foreground: '#e8e8ed',
      card: '#141416',
      'card-foreground': '#e8e8ed',
      primary: '#e5e5e5',
      'primary-foreground': '#0a0a0b',
      secondary: '#1e1e22',
      'secondary-foreground': '#e8e8ed',
      muted: '#1e1e22',
      'muted-foreground': '#8b8b96',
      accent: '#3b82f6',
      'accent-foreground': '#ffffff',
      destructive: '#ef4444',
      'destructive-foreground': '#ffffff',
      border: '#232328',
      input: '#1e1e22',
      ring: '#3b82f6',
      'status-success': '#22c55e',
      'status-warning': '#eab308',
      'status-error': '#ef4444',
      'status-info': '#3b82f6',
      'status-idle': '#6b7280',
      'diff-add-bg': 'rgba(34, 197, 94, 0.12)',
      'diff-add-fg': '#4ade80',
      'diff-del-bg': 'rgba(239, 68, 68, 0.12)',
      'diff-del-fg': '#f87171',
      'diff-context': '#8b8b96',
      'term-error': '#f87171',
      'term-success': '#4ade80',
      'term-warning': '#facc15',
      'term-muted': '#8b8b96',
      'gradient-start': '#3b82f6',
      'gradient-end': '#8b5cf6',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight Blue',
    colors: {
      background: '#0b0e14',
      foreground: '#c8ccd4',
      card: '#111620',
      'card-foreground': '#c8ccd4',
      primary: '#d4d4d8',
      'primary-foreground': '#0b0e14',
      secondary: '#1a1f2e',
      'secondary-foreground': '#c8ccd4',
      muted: '#1a1f2e',
      'muted-foreground': '#6b7280',
      accent: '#6366f1',
      'accent-foreground': '#ffffff',
      destructive: '#f43f5e',
      'destructive-foreground': '#ffffff',
      border: '#1e2433',
      input: '#1a1f2e',
      ring: '#6366f1',
      'status-success': '#34d399',
      'status-warning': '#fbbf24',
      'status-error': '#f43f5e',
      'status-info': '#6366f1',
      'status-idle': '#4b5563',
      'diff-add-bg': 'rgba(52, 211, 153, 0.12)',
      'diff-add-fg': '#34d399',
      'diff-del-bg': 'rgba(244, 63, 94, 0.12)',
      'diff-del-fg': '#fb7185',
      'diff-context': '#6b7280',
      'term-error': '#fb7185',
      'term-success': '#34d399',
      'term-warning': '#fbbf24',
      'term-muted': '#6b7280',
      'gradient-start': '#6366f1',
      'gradient-end': '#a855f7',
    },
  },
  {
    id: 'light',
    name: 'Light',
    colors: {
      background: '#fafafa',
      foreground: '#18181b',
      card: '#ffffff',
      'card-foreground': '#18181b',
      primary: '#18181b',
      'primary-foreground': '#ffffff',
      secondary: '#f4f4f5',
      'secondary-foreground': '#18181b',
      muted: '#f4f4f5',
      'muted-foreground': '#71717a',
      accent: '#2563eb',
      'accent-foreground': '#ffffff',
      destructive: '#dc2626',
      'destructive-foreground': '#ffffff',
      border: '#e4e4e7',
      input: '#e4e4e7',
      ring: '#2563eb',
      'status-success': '#16a34a',
      'status-warning': '#ca8a04',
      'status-error': '#dc2626',
      'status-info': '#2563eb',
      'status-idle': '#9ca3af',
      'diff-add-bg': 'rgba(22, 163, 74, 0.1)',
      'diff-add-fg': '#16a34a',
      'diff-del-bg': 'rgba(220, 38, 38, 0.1)',
      'diff-del-fg': '#dc2626',
      'diff-context': '#71717a',
      'term-error': '#dc2626',
      'term-success': '#16a34a',
      'term-warning': '#ca8a04',
      'term-muted': '#71717a',
      'gradient-start': '#2563eb',
      'gradient-end': '#7c3aed',
    },
  },
];

export function applyTheme(themeId: string) {
  const theme = themes.find((t) => t.id === themeId);
  if (!theme) return;

  const root = document.documentElement;
  Object.entries(theme.colors).forEach(([key, value]) => {
    root.style.setProperty(`--${key}`, value);
  });
}
